version: "3.2"
services:
  messagedb:
    image: mongo:3.4.9-jessie
    networks:
      - mongomessage
    deploy:
      placement:
        constraints:
           - 'node.platform.arch == x86_64'
  webX64:
    image: fpommerening/devopenspace2017:mongomessage
    ports:
        - 5000:5000
    networks:
        - mongomessage
    depends_on:
        - messagedb
    deploy:
      placement:
        constraints:
          - 'node.platform.arch == x86_64'
      environment:
        - MessageConnectionString=mongodb://messagedb  
  webArm:
    image: fpommerening/dotnetinthebox:raspi
    ports:
      - 5001:5000
    networks:
      - mongomessage
    deploy:
      placement:
        constraints:
          - 'node.platform.arch == armv7l'
networks:
  mongomessage:
